module Bugzilla
  module Tracer
    class TraceExecution
      INVALID_EVENT_MESSAGE: untyped

      @block: untyped

      private

      def begin_trace: -> untyped

      def run_trace: -> untyped
    end
  end
end
