name: Ruby

on:
  push:
    branches:
        - master

steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true
    - name: Install Gems
            run: |
                bundle install

    - name: Build and test with RSpec
            env:
                PG_DATABASE: postgres
                PG_HOST: localhost
                PG_USER: postgres
                PG_PASSWORD: password
                RAILS_ENV: test
            run: |
                bundle exec rspec spec



#   pull_request:
#
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: Ruby ${{ matrix.ruby }}
#     strategy:
#       matrix:
#         ruby:
#           - '3.2.0'
#
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Ruby
#       uses: ruby/setup-ruby@v1
#       with:
#         ruby-version: ${{ matrix.ruby }}
#         bundler-cache: true
#     - name: Run the default task
#       run: bundle exec rake
